"""add rating and author

Revision ID: 654e32fc5ffc
Revises: b56ddf0fa91f
Create Date: 2026-09-18 14:57:23.559195

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '654e32fc5ffc'
down_revision: Union[str, Sequence[str], None] = 'b56ddf0fa91f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reviews', sa.Column('author', sa.String(), nullable=True))
    op.add_column('reviews', sa.Column('rating', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reviews', 'rating')
    op.drop_column('reviews', 'author')
    # ### end Alembic commands ###
